import { useEffect, useId, useRef, useState } from "react";
import { Globe2, Menu, X } from "lucide-react";
import type { Locale } from "../content";
import { localeLabels, localePaths, locales } from "../content";
import BrandMark from "./BrandMark";

export default function AccessibleSiteHeader({ locale, navItems, navLabel, openLabel, closeLabel }: { locale: Locale; navItems: readonly (readonly [string,string])[]; navLabel: string; openLabel: string; closeLabel: string }) {
  const [open,setOpen]=useState(false); const id=useId(); const root=useRef<HTMLElement>(null); const toggle=useRef<HTMLButtonElement>(null); const first=useRef<HTMLAnchorElement>(null);
  const close=(restore=false)=>{setOpen(false);if(restore)requestAnimationFrame(()=>toggle.current?.focus())};
  useEffect(()=>{if(!open)return;first.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.preventDefault();close(true);return}if(event.key!=="Tab")return;const items=Array.from(root.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled])')??[]).filter(item=>item.offsetParent!==null&&!item.classList.contains("nav-backdrop"));const start=items[0],end=items[items.length-1];if(event.shiftKey&&document.activeElement===start){event.preventDefault();end?.focus()}else if(!event.shiftKey&&document.activeElement===end){event.preventDefault();start?.focus()}};const resize=()=>{if(innerWidth>860)setOpen(false)};addEventListener("keydown",key);addEventListener("resize",resize);addEventListener("orientationchange",resize);return()=>{removeEventListener("keydown",key);removeEventListener("resize",resize);removeEventListener("orientationchange",resize)}},[open]);
  return <header ref={root} className="site-header" data-open={open}><div className="nav-shell" aria-label={navLabel}><BrandMark href="#top"/><button ref={toggle} className="icon-button nav-toggle" type="button" aria-label={open?closeLabel:openLabel} aria-expanded={open} aria-controls={id} onClick={()=>setOpen(value=>!value)}>{open?<X aria-hidden="true"/>:<Menu aria-hidden="true"/>}</button><div className="mobile-nav-panel" id={id}><nav className="primary-nav" aria-label={navLabel}>{navItems.map(([href,label],index)=><a key={href} ref={index===0?first:undefined} href={href} onClick={()=>close()}>{label}</a>)}</nav><div className="language-switcher" aria-label="Language"><Globe2 aria-hidden="true"/>{locales.map(item=><a key={item} href={localePaths[item]} aria-current={locale===item?"page":undefined}>{localeLabels[item]}</a>)}</div></div></div>{open&&<button className="nav-backdrop" type="button" aria-label={closeLabel} onClick={()=>close(true)}/>}</header>;
}
