import { FormEvent, useMemo, useState } from "react";
import { ArrowUpRight, Camera, CheckCircle2, ChevronRight, Download, ExternalLink, FileArchive, Globe2, Mail, MapPin, Menu, MonitorSmartphone, PenLine, Phone, Send, ShieldCheck, Sparkles, UsersRound, X } from "lucide-react";
import { content, localeLabels, localePaths, locales, type Locale } from "./content";
import { projectData, type ProjectCard, type ProjectPreviewKind } from "./projectData";
import { getCompany } from "./company";
import { trackEvent } from "./analytics";

const formEndpoint = "https://formspree.io/f/mpwdpqzk";
type ProjectType = "" | "web" | "photo" | "content" | "multilingual" | "tools";
type FormStatus = "idle" | "sending" | "success" | "error";
type FormData = { name:string; email:string; company:string; projectType:ProjectType; timeline:string; budget:string; reference:string; message:string; website:string; consent:boolean };
const emptyForm: FormData = { name:"", email:"", company:"", projectType:"", timeline:"", budget:"", reference:"", message:"", website:"", consent:false };

const labels = {
  ko: { skip:"본문으로 이동", nav:"주요 메뉴", menu:"메뉴", close:"메뉴 닫기", services:"Services", serviceTitle:"지금 시작할 수 있는 서비스", serviceIntro:"현재 필요한 범위를 함께 정하고 실제로 사용할 수 있는 작은 결과물부터 제작합니다.", inquiry:"이 서비스로 문의", work:"Selected Work", trust:"작게 시작해도 운영 가능한 형태로", trustItems:["PC와 모바일 실제 화면 검수","도메인 연결과 배포 구조 정리","한국어 기준 영어·일본어 확장 대응","오픈 이후 직접 수정할 수 있는 운영 방식 안내"], faq:"자주 묻는 내용", faqs:[["자료가 완전히 준비되지 않아도 되나요?","현재 가지고 있는 로고, 사진, 메모와 참고 사이트부터 확인하고 부족한 내용을 함께 정리합니다."],["공개 후 직접 수정할 수 있나요?","자주 바뀌는 내용과 고정 영역을 나누고 관리하기 쉬운 구조를 제안합니다."],["사진과 홈페이지를 함께 진행할 수 있나요?","필요한 이미지 비율과 용도를 먼저 정하면 하나의 브랜드 화면으로 자연스럽게 연결할 수 있습니다."]], projectType:"문의 유형", projectOptions:{web:"홈페이지·포트폴리오",photo:"사진·시각 콘텐츠",content:"브랜드 문구·콘텐츠",multilingual:"다국어·운영 구조",tools:"웹 도구·작은 서비스"}, timeline:"희망 일정", timelines:["가능한 빠르게","1개월 이내","2~3개월 이내","일정 상담 필요"], budget:"예상 예산", budgets:["아직 정해지지 않음","30만 원 미만","30만~50만 원","50만~100만 원","100만 원 이상","상담 후 결정"], reference:"참고 링크 (선택)", company:"브랜드·회사명 (선택)", submit:"문의 보내기", sending:"전송 중", success:"문의가 접수되었습니다. 확인 후 답변드리겠습니다.", error:"전송이 원활하지 않습니다. 이메일로 직접 문의해주세요.", consent:"개인정보 수집 및 답변 목적 이용에 동의합니다.", mobile:"프로젝트 문의" },
  en: { skip:"Skip to content", nav:"Main navigation", menu:"Menu", close:"Close menu", services:"Services", serviceTitle:"Services you can start with", serviceIntro:"We define a realistic scope together and begin with something you can actually use.", inquiry:"Ask about this service", work:"Selected Work", trust:"Start small and launch something operational", trustItems:["Real-device checks on desktop and mobile","Domain connection and deployment setup","English and Japanese expansion from Korean content","Guidance for maintaining content after launch"], faq:"Frequently asked questions", faqs:[["Can we start before all materials are ready?","Yes. We can begin with your current logo, photos, notes, and reference sites."],["Can I update the site after launch?","We separate changing content from fixed areas and suggest a practical maintenance structure."],["Can photography and website production be combined?","Yes. Defining image needs before the shoot creates a more coherent brand experience."]], projectType:"Inquiry type", projectOptions:{web:"Website or portfolio",photo:"Photography and visuals",content:"Brand copy and content",multilingual:"Multilingual structure",tools:"Web tools and small services"}, timeline:"Preferred timeline", timelines:["As soon as possible","Within one month","Within two to three months","Consultation needed"], budget:"Estimated budget", budgets:["Not decided yet","Under KRW 300,000","KRW 300,000–500,000","KRW 500,000–1,000,000","Over KRW 1,000,000","Decide after consultation"], reference:"Reference link (optional)", company:"Brand or company (optional)", submit:"Send inquiry", sending:"Sending", success:"Your inquiry has been received.", error:"The form could not be sent. Please contact us by email.", consent:"I agree to the use of my information for a response.", mobile:"Project inquiry" },
  jp: { skip:"本文へ移動", nav:"メインナビゲーション", menu:"メニュー", close:"メニューを閉じる", services:"Services", serviceTitle:"今から始められるサービス", serviceIntro:"必要な範囲を一緒に決め、実際に使える小さな成果物から制作します。", inquiry:"このサービスを相談", work:"Selected Work", trust:"小さく始めても、実際に運営できる形へ", trustItems:["PC・スマートフォン実機での確認","ドメイン接続と公開構成の整理","韓国語を基準に英語・日本語へ拡張","公開後に更新しやすい運営方法の案内"], faq:"よくあるご質問", faqs:[["素材が揃っていなくても始められますか？","現在お持ちのロゴ、写真、メモ、参考サイトから確認できます。"],["公開後に自分で更新できますか？","更新内容と固定部分を分け、管理しやすい構成をご提案します。"],["写真撮影とサイト制作を一緒に依頼できますか？","必要な画像比率を先に決めることで、一つのブランド体験としてつなげられます。"]], projectType:"お問い合わせ種別", projectOptions:{web:"Webサイト・ポートフォリオ",photo:"写真・ビジュアル",content:"ブランド文章・構成",multilingual:"多言語・運営構成",tools:"Webツール・小規模サービス"}, timeline:"希望日程", timelines:["できるだけ早く","1か月以内","2〜3か月以内","日程相談が必要"], budget:"想定予算", budgets:["未定","30万ウォン未満","30万〜50万ウォン","50万〜100万ウォン","100万ウォン以上","相談後に決定"], reference:"参考リンク（任意）", company:"ブランド・会社名（任意）", submit:"送信する", sending:"送信中", success:"お問い合わせを受け付けました。", error:"送信できませんでした。メールでご連絡ください。", consent:"回答のための個人情報利用に同意します。", mobile:"プロジェクト相談" }
} as const;

const localeFromPath = (): Locale => location.pathname.startsWith("/en") ? "en" : location.pathname.startsWith("/jp") ? "jp" : "ko";

function BrandMark(){ return <picture className="brand-mark"><source srcSet="/assets/images/lava-logo-transparent-160.webp" type="image/webp"/><img src="/assets/images/lava-logo-transparent.png" alt="Lava Labs" width="40" height="40"/></picture>; }

function ProjectPreview({ kind, title }: { kind: ProjectPreviewKind; title:string }){
  if(kind === "softmoon") return <div className="case-preview project-image-preview softmoon"><img src="/assets/images/lunar-sample-1-720.webp" alt="" loading="lazy" width="1200" height="800"/><div className="case-preview-label"><strong>{title}</strong></div></div>;
  const domain = kind === "snap" ? "snap.lavalabs.co.kr" : kind === "follow" ? "unfollow.lavalabs.co.kr" : "emoseed.lavalabs.co.kr";
  return <div className={`case-preview project-static-preview project-${kind}-preview`}><div className="preview-window"><span/><span/><span/><small>{domain}</small></div><div className="preview-dashboard" aria-hidden="true">{kind === "follow" ? <><div><UsersRound/><b>Mutual</b></div><div><ShieldCheck/><b>Local</b></div><div><FileArchive/><b>ZIP</b></div></> : kind === "emoseed" ? <><div><Sparkles/><b>Plant Test</b></div><div><MonitorSmartphone/><b>Daily</b></div><div><CheckCircle2/><b>Share</b></div></> : <><i/><i/><i/></>}</div><div className="case-preview-label"><strong>{title}</strong><small>Static preview</small></div></div>;
}

function ProjectCardView({project,locale}:{project:ProjectCard;locale:Locale}){
  const external=project.href.startsWith("http");
  return <article className={`case-card project-${project.preview}`}><ProjectPreview kind={project.preview} title={project.title}/><div className="case-content"><div className="case-status-row"><span className={`case-status ${project.preview === "follow" ? "beta-status" : ""}`}>{project.status}</span>{project.statusDetail&&<small>{project.statusDetail}</small>}</div><h3>{project.title}</h3><p className="case-type">{project.type}</p><p>{project.body}</p>{project.notice&&<p className="case-notice"><ShieldCheck/><span>{project.notice}</span></p>}<div className="tag-row">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="case-actions"><a href={project.href} target={external?"_blank":undefined} rel={external?"noreferrer":undefined} onClick={()=>trackEvent("portfolio_visit",{locale,project:project.title})}>{project.cta}<ExternalLink/></a>{project.detailHref&&<a className="case-secondary-link" href={project.detailHref}>{project.detailCta}<ChevronRight/></a>}</div></div></article>;
}

export default function ProjectHomepage(){
  const locale=localeFromPath(); const t=content[locale]; const p=projectData[locale]; const u=labels[locale]; const company=getCompany();
  const [menuOpen,setMenuOpen]=useState(false); const [status,setStatus]=useState<FormStatus>("idle"); const [form,setForm]=useState<FormData>(emptyForm); const currentYear=useMemo(()=>new Date().getFullYear(),[]);
  const services=[...t.services,p.webToolService]; const operating=p.projects.filter(item=>item.group==="operating"); const research=p.projects.filter(item=>item.group==="research");
  const submit=async(event:FormEvent<HTMLFormElement>)=>{ event.preventDefault(); if(form.website)return; setStatus("sending"); try{const response=await fetch(formEndpoint,{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({...form,locale,source:"lavalabs.co.kr inquiry"})}); if(!response.ok)throw new Error(); setStatus("success"); setForm(emptyForm);}catch{setStatus("error");}};
  const serviceIcons=[MonitorSmartphone,Camera,PenLine,Sparkles,MonitorSmartphone];
  return <div className="app-shell home-upgraded"><a className="skip-link" href="#main-content">{u.skip}</a><header className="site-header" data-open={menuOpen}><div className="nav-shell" aria-label={u.nav}><a className="brand-link" href="#top"><BrandMark/><span>Lava Labs</span></a><button className="icon-button nav-toggle" type="button" aria-label={menuOpen?u.close:u.menu} onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?<X/>:<Menu/>}</button><nav className="primary-nav">{t.nav.map(([href,label])=><a key={href} href={href} onClick={()=>setMenuOpen(false)}>{label}</a>)}</nav><div className="language-switcher" aria-label="Language"><Globe2/>{locales.map(item=><a key={item} href={localePaths[item]} aria-current={locale===item?"page":undefined}>{localeLabels[item]}</a>)}</div></div></header>
  <main id="main-content"><section className="hero" id="top"><div className="section-inner hero-inner"><p className="eyebrow">{t.hero.eyebrow}</p><h1>{t.hero.title}</h1><p className="hero-statement">{t.hero.statement}</p><p className="hero-copy">{t.hero.body}</p><p className="hero-addon"><MonitorSmartphone/>{p.heroAddon}</p><div className="hero-actions"><a className="button primary" href="#contact"><Send/>{t.hero.primary}</a><a className="button secondary" href="#projects">{t.hero.secondary}<ChevronRight/></a></div></div></section>
  <section className="proof-strip"><div className="section-inner proof-grid">{t.hero.proof.map(([value,label])=><div className="proof-item" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
  <section className="section about-section" id="about"><div className="section-inner two-column"><div className="section-heading"><p className="eyebrow">{t.about.kicker}</p><h2>{t.about.title}</h2></div><div className="body-copy"><p>{t.about.body}</p><ul className="check-list">{t.about.highlights.map(item=><li key={item}><CheckCircle2/><span>{item}</span></li>)}</ul></div></div></section>
  <section className="section muted-section" id="services"><div className="section-inner"><div className="section-heading compact"><p className="eyebrow">{u.services}</p><h2>{u.serviceTitle}</h2><p>{u.serviceIntro}</p></div><div className="service-grid">{services.map((service,index)=>{const Icon=serviceIcons[index]; const types:ProjectType[]=["web","photo","content","multilingual","tools"];return <article className="service-card" key={service.title}><div className="service-icon"><Icon/></div><h3>{service.title}</h3><p>{service.body}</p><div className="tag-row">{service.tags.map(tag=><span key={tag}>{tag}</span>)}</div><a className="service-link" href="#contact" onClick={()=>setForm(data=>({...data,projectType:types[index]}))}>{u.inquiry}<ChevronRight/></a></article>})}</div></div></section>
  <section className="section portfolio-section projects-upgraded" id="projects"><div className="section-inner upgraded-project-inner"><div className="section-heading compact"><p className="eyebrow">{u.work}</p><h2>{p.title}</h2><p>{p.intro}</p></div><div className="project-group"><div className="project-group-heading"><h3>{p.operatingTitle}</h3><p>{p.operatingIntro}</p></div><div className="case-grid operating-projects">{operating.map(project=><ProjectCardView key={project.title} project={project} locale={locale}/>)}</div></div><div className="project-group"><div className="project-group-heading"><h3>{p.researchTitle}</h3><p>{p.researchIntro}</p></div><div className="case-grid research-projects">{research.map(project=><ProjectCardView key={project.title} project={project} locale={locale}/>)}</div></div><p className="site-build-note"><CheckCircle2/>{p.siteNote}</p></div></section>
  <section className="section split-band"><div className="section-inner split-layout"><div><div className="section-heading"><p className="eyebrow">Reliable Delivery</p><h2>{u.trust}</h2></div><ul className="project-list">{u.trustItems.map(item=><li key={item}><CheckCircle2/><span>{item}</span></li>)}</ul></div><div className="process-panel"><p className="eyebrow">Process</p><h2>{t.processTitle}</h2><ol className="process-list">{t.process.map(([title,body])=><li key={title}><strong>{title}</strong><span>{body}</span></li>)}</ol></div></div></section>
  <section className="section softmoon-section" id="softmoon"><div className="section-inner softmoon-layout"><div className="softmoon-copy"><p className="eyebrow">{t.softMoon.kicker}</p><h2>{t.softMoon.title}</h2><p>{t.softMoon.body}</p><div className="button-row"><a className="button primary" href={locale==="ko"?"/soft_moon/":`/${locale}/soft_moon/`}>{t.softMoon.view}<ArrowUpRight/></a><a className="button ghost" href="/assets/files/softmoon-intro.pdf" download><Download/>{t.softMoon.download}</a></div></div><div className="softmoon-gallery"><img src="/assets/images/lunar-sample-1-720.webp" alt="SoftMoon paper goods" loading="lazy" width="720" height="900"/><img src="/assets/images/lunar-sample-2-720.webp" alt="SoftMoon product sample" loading="lazy" width="720" height="900"/></div></div></section>
  <section className="section faq-section"><div className="section-inner faq-layout"><div className="section-heading"><p className="eyebrow">Before We Start</p><h2>{u.faq}</h2></div><div className="faq-list">{u.faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronRight/></summary><p>{a}</p></details>)}</div></div></section>
  <section className="section contact-section" id="contact"><div className="section-inner contact-layout"><div className="contact-copy"><p className="eyebrow">{t.contact.kicker}</p><h2>{t.contact.title}</h2><p>{t.contact.body}</p><div className="contact-methods"><a href={`tel:${t.contact.tel.replace(/-/g,"")}`}><Phone/>{t.contact.tel}</a><a href={`mailto:${company.email}`}><Mail/>{company.email}</a><span><MapPin/>{company.address[locale]||t.contact.address}</span></div></div><form className="contact-form enhanced-contact-form" onSubmit={submit}><div className="form-pair"><label><span>{t.contact.name}</span><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>{t.contact.email}</span><input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><div className="form-pair"><label><span>{u.company}</span><input value={form.company} onChange={e=>setForm({...form,company:e.target.value})}/></label><label><span>{u.projectType}</span><select name="projectType" required value={form.projectType} onChange={e=>setForm({...form,projectType:e.target.value as ProjectType})}><option value="">-</option>{Object.entries(u.projectOptions).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><div className="form-pair"><label><span>{u.timeline}</span><select required value={form.timeline} onChange={e=>setForm({...form,timeline:e.target.value})}><option value="">-</option>{u.timelines.map(value=><option key={value}>{value}</option>)}</select></label><label><span>{u.budget}</span><select required value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}><option value="">-</option>{u.budgets.map(value=><option key={value}>{value}</option>)}</select></label></div><label><span>{u.reference}</span><input type="url" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label><span>{t.contact.message}</span><textarea rows={7} required value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><label className="honeypot" aria-hidden="true"><input name="website" tabIndex={-1} value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/></label><label className="consent-row"><input type="checkbox" required checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>{u.consent} <a href="/privacy/">Privacy</a></span></label><button className="button primary submit-button" type="submit" disabled={status==="sending"}><Send/>{status==="sending"?u.sending:u.submit}</button>{status!=="idle"&&<div className={`form-status ${status}`} role="status"><p>{status==="success"?u.success:status==="error"?u.error:u.sending}</p></div>}</form></div></section></main>
  <footer className="site-footer"><div className="section-inner footer-layout"><div><a className="brand-link" href="/"><BrandMark/><span>Lava Labs</span></a><p>{t.footer}</p></div><div className="footer-links"><a href={company.kakao} target="_blank" rel="noreferrer">KakaoTalk</a><a href={company.instagram} target="_blank" rel="noreferrer">Instagram</a><a href="/terms/">Terms</a><a href="/privacy/">Privacy</a></div><small>(c) {currentYear} Lava Labs. All rights reserved.</small></div></footer><a className="mobile-contact-bar" href="#contact"><Send/>{u.mobile}</a></div>;
}
